theme: minima

title: "Yo I'm Trijit"
description: ""
author: Trijit

url: "https://yo-im-trijit.github.io"
baseurl: ""

show_excerpts: true

minima:
  skin: dark

markdown: kramdown

include:
  - assets
